// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace MimunYashirPersistence.CompiledModels
{
    public partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var contract = ContractEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var package = PackageEntityType.Create(this);

            ContractEntityType.CreateForeignKey1(contract, customer);
            PackageEntityType.CreateForeignKey1(package, contract);

            ContractEntityType.CreateAnnotations(contract);
            CustomerEntityType.CreateAnnotations(customer);
            PackageEntityType.CreateAnnotations(package);

            AddAnnotation("ProductVersion", "7.0.3");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
